language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV="py36--django{1.11,2.0,2.1,2.2,3.0}"
        - python: 3.7
          env: TOXENV="py37--django{2.0,2.1,2.2,3.0}"
install:
  - pip install tox
script:
  - tox
sudo: false
notifications:
    email: false
